"""PA Firewall model specifications for sizing calculations.

Specs sourced from Palo Alto Networks product datasheets and
https://www.paloaltonetworks.com/products/product-selection

All throughput values in Mbps (App-ID Appmix). Session counts are maximums.
SD-WAN IPSec tunnel counts are from official SD-WAN specifications.
"""

from collections import OrderedDict

# TAC recommended PAN-OS versions per series
TAC_RECOMMENDED_PANOS = OrderedDict([
    ('PA-400', '11.1.6 or 11.2.4'),
    ('PA-500', '11.2.4 or 12.0.1'),
    ('PA-800', '11.1.6 or 11.2.4'),
    ('PA-1400', '11.2.4 or 12.0.1'),
    ('PA-3400', '11.1.6 or 11.2.4'),
    ('PA-5400', '11.1.6 or 11.2.4'),
    ('PA-7000', '11.1.6 or 11.2.4'),
    ('VM-Series', '11.1.6 or 11.2.4'),
])

# Hardware models — ordered smallest to largest
PA_MODELS = OrderedDict([
    ('PA-410', {
        'series': 'PA-400',
        'platform': 'hardware',
        'firewall_throughput': 1400,
        'threat_throughput': 800,
        'ipsec_vpn_throughput': 650,
        'ssl_decrypt_throughput': 400,
        'max_sessions': 64000,
        'new_sessions_per_sec': 11000,
        'max_ipsec_tunnels': 1000,
        'max_security_rules': 500,
        'recommended_role': 'branch',
        'form_factor': 'Desktop',
        'ha_supported': False,
        'sdwan_supported': True,
        'ports': '7x 1G',
        'power_supply': 'Single',
        'sdwan_rules': 32,
        'sdwan_virtual_interfaces': 16,
        'max_zones': 16,
        'max_virtual_routers': 1,
        'use_case': 'Micro-branch, home office, retail kiosk',
        'description': 'Entry-level branch firewall for micro/small offices',
    }),
    ('PA-440', {
        'series': 'PA-400',
        'platform': 'hardware',
        'firewall_throughput': 2600,
        'threat_throughput': 1200,
        'ipsec_vpn_throughput': 1100,
        'ssl_decrypt_throughput': 550,
        'max_sessions': 198976,
        'new_sessions_per_sec': 34000,
        'max_ipsec_tunnels': 2800,
        'max_security_rules': 2000,
        'recommended_role': 'branch',
        'form_factor': 'Desktop',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G',
        'power_supply': 'Single',
        'sdwan_rules': 64,
        'sdwan_virtual_interfaces': 32,
        'max_zones': 32,
        'max_virtual_routers': 2,
        'use_case': 'Small branch office, retail store',
        'description': 'Mid-range branch firewall for small offices',
    }),
    ('PA-450', {
        'series': 'PA-400',
        'platform': 'hardware',
        'firewall_throughput': 3300,
        'threat_throughput': 2100,
        'ipsec_vpn_throughput': 1700,
        'ssl_decrypt_throughput': 960,
        'max_sessions': 300000,
        'new_sessions_per_sec': 48000,
        'max_ipsec_tunnels': 2800,
        'max_security_rules': 2500,
        'recommended_role': 'branch',
        'form_factor': 'Desktop',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G',
        'power_supply': 'Single',
        'sdwan_rules': 64,
        'sdwan_virtual_interfaces': 32,
        'max_zones': 32,
        'max_virtual_routers': 2,
        'use_case': 'Medium branch office, regional office',
        'description': 'Mid-range branch firewall for medium offices',
    }),
    ('PA-460', {
        'series': 'PA-400',
        'platform': 'hardware',
        'firewall_throughput': 4600,
        'threat_throughput': 3000,
        'ipsec_vpn_throughput': 2300,
        'ssl_decrypt_throughput': 1440,
        'max_sessions': 400000,
        'new_sessions_per_sec': 67000,
        'max_ipsec_tunnels': 2800,
        'max_security_rules': 2500,
        'recommended_role': 'branch',
        'form_factor': 'Desktop',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G',
        'power_supply': 'Single',
        'sdwan_rules': 64,
        'sdwan_virtual_interfaces': 32,
        'max_zones': 32,
        'max_virtual_routers': 2,
        'use_case': 'Large branch office, campus edge',
        'description': 'High-performance branch firewall',
    }),
    ('PA-540', {
        'series': 'PA-500',
        'platform': 'hardware',
        'firewall_throughput': 3800,
        'threat_throughput': 2200,
        'ipsec_vpn_throughput': 2000,
        'ssl_decrypt_throughput': 1100,
        'max_sessions': 298849,
        'new_sessions_per_sec': 50000,
        'max_ipsec_tunnels': 2800,
        'max_security_rules': 2500,
        'recommended_role': 'branch',
        'form_factor': 'Desktop',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G, 2x SFP',
        'power_supply': 'Single',
        'sdwan_rules': 64,
        'sdwan_virtual_interfaces': 32,
        'max_zones': 32,
        'max_virtual_routers': 2,
        'use_case': 'Next-gen branch with fiber uplinks',
        'description': 'Next-gen branch firewall with SFP uplinks',
    }),
    ('PA-820', {
        'series': 'PA-800',
        'platform': 'hardware',
        'firewall_throughput': 1500,
        'threat_throughput': 840,
        'ipsec_vpn_throughput': 1400,
        'ssl_decrypt_throughput': 580,
        'max_sessions': 128000,
        'new_sessions_per_sec': 8100,
        'max_ipsec_tunnels': 1000,
        'max_security_rules': 1500,
        'recommended_role': 'branch',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '4x 1G, 8x SFP',
        'power_supply': 'Redundant',
        'sdwan_rules': 64,
        'sdwan_virtual_interfaces': 32,
        'max_zones': 40,
        'max_virtual_routers': 3,
        'use_case': 'Branch office requiring rack-mount with redundant power',
        'description': 'Rack-mount branch firewall with redundant power',
    }),
    ('PA-850', {
        'series': 'PA-800',
        'platform': 'hardware',
        'firewall_throughput': 2100,
        'threat_throughput': 1200,
        'ipsec_vpn_throughput': 1600,
        'ssl_decrypt_throughput': 700,
        'max_sessions': 192000,
        'new_sessions_per_sec': 13000,
        'max_ipsec_tunnels': 1000,
        'max_security_rules': 1500,
        'recommended_role': 'branch',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '4x 1G, 8x SFP, 4x SFP+',
        'power_supply': 'Redundant',
        'sdwan_rules': 64,
        'sdwan_virtual_interfaces': 32,
        'max_zones': 40,
        'max_virtual_routers': 3,
        'use_case': 'Large branch with 10G uplink requirements',
        'description': 'High-end branch firewall with 10G uplinks',
    }),
    ('PA-1410', {
        'series': 'PA-1400',
        'platform': 'hardware',
        'firewall_throughput': 8500,
        'threat_throughput': 4500,
        'ipsec_vpn_throughput': 4100,
        'ssl_decrypt_throughput': 2200,
        'max_sessions': 945000,
        'new_sessions_per_sec': 100000,
        'max_ipsec_tunnels': 2800,
        'max_security_rules': 10000,
        'recommended_role': 'both',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G, 4x 2.5G/5G, 6x SFP, 4x SFP+',
        'power_supply': 'Single',
        'sdwan_rules': 128,
        'sdwan_virtual_interfaces': 64,
        'max_zones': 64,
        'max_virtual_routers': 5,
        'use_case': 'Enterprise branch, small hub, campus gateway',
        'description': 'Entry-level enterprise branch or small hub firewall',
    }),
    ('PA-1420', {
        'series': 'PA-1400',
        'platform': 'hardware',
        'firewall_throughput': 9500,
        'threat_throughput': 6200,
        'ipsec_vpn_throughput': 5600,
        'ssl_decrypt_throughput': 3000,
        'max_sessions': 1398646,
        'new_sessions_per_sec': 140000,
        'max_ipsec_tunnels': 2800,
        'max_security_rules': 10000,
        'recommended_role': 'both',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '4x 1G, 8x 2.5G/5G, 2x SFP, 8x SFP+',
        'power_supply': 'Redundant',
        'sdwan_rules': 128,
        'sdwan_virtual_interfaces': 64,
        'max_zones': 64,
        'max_virtual_routers': 5,
        'use_case': 'Enterprise branch, small hub with redundant power',
        'description': 'Enterprise branch or small hub firewall',
    }),
    ('PA-3410', {
        'series': 'PA-3400',
        'platform': 'hardware',
        'firewall_throughput': 14000,
        'threat_throughput': 7500,
        'ipsec_vpn_throughput': 6600,
        'ssl_decrypt_throughput': 3400,
        'max_sessions': 1400000,
        'new_sessions_per_sec': 145000,
        'max_ipsec_tunnels': 3000,
        'max_security_rules': 10000,
        'recommended_role': 'both',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '12x 1G/10G, 10x SFP+, 4x SFP28',
        'power_supply': 'Redundant',
        'sdwan_rules': 256,
        'sdwan_virtual_interfaces': 128,
        'max_zones': 128,
        'max_virtual_routers': 10,
        'use_case': 'Regional hub, large campus, datacenter edge',
        'description': 'Mid-enterprise firewall for hub or large branch',
    }),
    ('PA-3420', {
        'series': 'PA-3400',
        'platform': 'hardware',
        'firewall_throughput': 19000,
        'threat_throughput': 10000,
        'ipsec_vpn_throughput': 9900,
        'ssl_decrypt_throughput': 4500,
        'max_sessions': 2200000,
        'new_sessions_per_sec': 205000,
        'max_ipsec_tunnels': 3000,
        'max_security_rules': 10000,
        'recommended_role': 'hub',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '12x 1G/10G, 10x SFP+, 4x SFP28',
        'power_supply': 'Redundant',
        'sdwan_rules': 256,
        'sdwan_virtual_interfaces': 128,
        'max_zones': 128,
        'max_virtual_routers': 10,
        'use_case': 'Enterprise hub, multi-site aggregation',
        'description': 'Enterprise hub firewall',
    }),
    ('PA-3430', {
        'series': 'PA-3400',
        'platform': 'hardware',
        'firewall_throughput': 29000,
        'threat_throughput': 15000,
        'ipsec_vpn_throughput': 12000,
        'ssl_decrypt_throughput': 6500,
        'max_sessions': 2500000,
        'new_sessions_per_sec': 240000,
        'max_ipsec_tunnels': 4000,
        'max_security_rules': 30000,
        'recommended_role': 'hub',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '12x 1G/10G, 10x SFP+, 4x SFP28, 2x QSFP28',
        'power_supply': 'Redundant',
        'sdwan_rules': 256,
        'sdwan_virtual_interfaces': 128,
        'max_zones': 128,
        'max_virtual_routers': 10,
        'use_case': 'Large enterprise hub, regional datacenter',
        'description': 'Large enterprise hub firewall',
    }),
    ('PA-3440', {
        'series': 'PA-3400',
        'platform': 'hardware',
        'firewall_throughput': 35000,
        'threat_throughput': 20000,
        'ipsec_vpn_throughput': 14500,
        'ssl_decrypt_throughput': 8200,
        'max_sessions': 2990000,
        'new_sessions_per_sec': 268000,
        'max_ipsec_tunnels': 4000,
        'max_security_rules': 30000,
        'recommended_role': 'hub',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '12x 1G/10G, 10x SFP+, 4x SFP28, 2x QSFP28',
        'power_supply': 'Redundant',
        'sdwan_rules': 256,
        'sdwan_virtual_interfaces': 128,
        'max_zones': 128,
        'max_virtual_routers': 10,
        'use_case': 'Top-tier enterprise hub, high-capacity aggregation',
        'description': 'Top-of-line PA-3400 series for large hubs',
    }),
    ('PA-5410', {
        'series': 'PA-5400',
        'platform': 'hardware',
        'firewall_throughput': 52000,
        'threat_throughput': 35000,
        'ipsec_vpn_throughput': 20000,
        'ssl_decrypt_throughput': 15000,
        'max_sessions': 4990000,
        'new_sessions_per_sec': 270000,
        'max_ipsec_tunnels': 4000,
        'max_security_rules': 30000,
        'recommended_role': 'hub',
        'form_factor': '2U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G/10G, 12x SFP+, 4x SFP28, 4x QSFP28',
        'power_supply': 'Redundant',
        'sdwan_rules': 512,
        'sdwan_virtual_interfaces': 256,
        'max_zones': 256,
        'max_virtual_routers': 20,
        'use_case': 'Datacenter hub, service provider edge',
        'description': 'High-performance datacenter/hub firewall',
    }),
    ('PA-5420', {
        'series': 'PA-5400',
        'platform': 'hardware',
        'firewall_throughput': 70000,
        'threat_throughput': 50000,
        'ipsec_vpn_throughput': 28000,
        'ssl_decrypt_throughput': 22000,
        'max_sessions': 6990000,
        'new_sessions_per_sec': 370000,
        'max_ipsec_tunnels': 5000,
        'max_security_rules': 45000,
        'recommended_role': 'hub',
        'form_factor': '2U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G/10G, 12x SFP+, 4x SFP28, 4x QSFP28',
        'power_supply': 'Redundant',
        'sdwan_rules': 512,
        'sdwan_virtual_interfaces': 256,
        'max_zones': 256,
        'max_virtual_routers': 20,
        'use_case': 'Large datacenter hub, regional aggregation',
        'description': 'Large datacenter/regional hub firewall',
    }),
    ('PA-5430', {
        'series': 'PA-5400',
        'platform': 'hardware',
        'firewall_throughput': 82000,
        'threat_throughput': 60000,
        'ipsec_vpn_throughput': 42000,
        'ssl_decrypt_throughput': 29000,
        'max_sessions': 8990000,
        'new_sessions_per_sec': 380000,
        'max_ipsec_tunnels': 5000,
        'max_security_rules': 65000,
        'recommended_role': 'hub',
        'form_factor': '2U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G/10G, 12x SFP+, 4x SFP28, 4x QSFP28',
        'power_supply': 'Redundant',
        'sdwan_rules': 512,
        'sdwan_virtual_interfaces': 256,
        'max_zones': 256,
        'max_virtual_routers': 20,
        'use_case': 'High-end datacenter hub, global aggregation',
        'description': 'High-end datacenter/SD-WAN hub firewall',
    }),
    ('PA-5440', {
        'series': 'PA-5400',
        'platform': 'hardware',
        'firewall_throughput': 90000,
        'threat_throughput': 70000,
        'ipsec_vpn_throughput': 58000,
        'ssl_decrypt_throughput': 37000,
        'max_sessions': 23990000,
        'new_sessions_per_sec': 390000,
        'max_ipsec_tunnels': 8000,
        'max_security_rules': 65000,
        'recommended_role': 'hub',
        'form_factor': '2U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G/10G, 12x SFP+, 4x SFP28, 4x QSFP28',
        'power_supply': 'Redundant',
        'sdwan_rules': 512,
        'sdwan_virtual_interfaces': 256,
        'max_zones': 256,
        'max_virtual_routers': 20,
        'use_case': 'Top-tier datacenter hub, massive branch aggregation',
        'description': 'Top PA-5400 series datacenter firewall',
    }),
    ('PA-5445', {
        'series': 'PA-5400',
        'platform': 'hardware',
        'firewall_throughput': 90000,
        'threat_throughput': 76000,
        'ipsec_vpn_throughput': 64000,
        'ssl_decrypt_throughput': 40000,
        'max_sessions': 47990000,
        'new_sessions_per_sec': 449000,
        'max_ipsec_tunnels': 8000,
        'max_security_rules': 65000,
        'recommended_role': 'hub',
        'form_factor': '2U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G/10G, 12x SFP+, 4x SFP28, 4x QSFP28',
        'power_supply': 'Redundant',
        'sdwan_rules': 512,
        'sdwan_virtual_interfaces': 256,
        'max_zones': 256,
        'max_virtual_routers': 20,
        'use_case': 'Enhanced datacenter hub, high session-count environments',
        'description': 'Enhanced PA-5400 with higher session capacity',
    }),
    ('PA-5450', {
        'series': 'PA-5400',
        'platform': 'hardware',
        'firewall_throughput': 200000,
        'threat_throughput': 189000,
        'ipsec_vpn_throughput': 85000,
        'ssl_decrypt_throughput': 55000,
        'max_sessions': 99900000,
        'new_sessions_per_sec': 3600000,
        'max_ipsec_tunnels': 8000,
        'max_security_rules': 65000,
        'recommended_role': 'hub',
        'form_factor': '4U Chassis',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Modular (DPCs)',
        'power_supply': 'Redundant',
        'sdwan_rules': 512,
        'sdwan_virtual_interfaces': 256,
        'max_zones': 256,
        'max_virtual_routers': 20,
        'use_case': 'Modular datacenter hub, carrier-grade aggregation',
        'description': 'Modular chassis firewall for largest SD-WAN hubs',
    }),
    ('PA-7050', {
        'series': 'PA-7000',
        'platform': 'hardware',
        'firewall_throughput': 343000,
        'threat_throughput': 184000,
        'ipsec_vpn_throughput': 190000,
        'ssl_decrypt_throughput': 90000,
        'max_sessions': 245000000,
        'new_sessions_per_sec': 4000000,
        'max_ipsec_tunnels': 4000,
        'max_security_rules': 65000,
        'recommended_role': 'hub',
        'form_factor': '12U Chassis',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Modular (NPCs)',
        'power_supply': 'Redundant',
        'sdwan_rules': 512,
        'sdwan_virtual_interfaces': 512,
        'max_zones': 512,
        'max_virtual_routers': 20,
        'use_case': 'Largest SD-WAN hub, global backbone aggregation',
        'description': 'Chassis-based firewall for largest SD-WAN hubs',
    }),
    ('PA-7080', {
        'series': 'PA-7000',
        'platform': 'hardware',
        'firewall_throughput': 700000,
        'threat_throughput': 430000,
        'ipsec_vpn_throughput': 328000,
        'ssl_decrypt_throughput': 207000,
        'max_sessions': 416000000,
        'new_sessions_per_sec': 6000000,
        'max_ipsec_tunnels': 4000,
        'max_security_rules': 65000,
        'recommended_role': 'hub',
        'form_factor': '19U Chassis',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Modular (NPCs)',
        'power_supply': 'Redundant',
        'sdwan_rules': 512,
        'sdwan_virtual_interfaces': 512,
        'max_zones': 512,
        'max_virtual_routers': 20,
        'use_case': 'Massive SD-WAN hub, global backbone aggregation',
        'description': 'Largest chassis-based firewall for massive deployments',
    }),
])

# VM-Series models — ordered smallest to largest
VM_MODELS = OrderedDict([
    ('VM-50', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 200,
        'threat_throughput': 100,
        'ipsec_vpn_throughput': 100,
        'ssl_decrypt_throughput': 60,
        'max_sessions': 50000,
        'new_sessions_per_sec': 3000,
        'max_ipsec_tunnels': 250,
        'max_security_rules': 2500,
        'recommended_role': 'branch',
        'form_factor': 'Virtual (2 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'sdwan_rules': 32,
        'sdwan_virtual_interfaces': 16,
        'max_zones': 16,
        'max_virtual_routers': 1,
        'use_case': 'Lab, dev environment, micro-branch',
        'description': 'Smallest VM for lab, dev, or micro-branch',
    }),
    ('VM-100', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 2000,
        'threat_throughput': 1000,
        'ipsec_vpn_throughput': 1000,
        'ssl_decrypt_throughput': 600,
        'max_sessions': 50000,
        'new_sessions_per_sec': 3000,
        'max_ipsec_tunnels': 500,
        'max_security_rules': 5000,
        'recommended_role': 'branch',
        'form_factor': 'Virtual (2 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'sdwan_rules': 64,
        'sdwan_virtual_interfaces': 32,
        'max_zones': 32,
        'max_virtual_routers': 2,
        'use_case': 'Cloud branch, remote site VPN concentrator',
        'description': 'Small VM for branch or remote sites',
    }),
    ('VM-200', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 2000,
        'threat_throughput': 1000,
        'ipsec_vpn_throughput': 1000,
        'ssl_decrypt_throughput': 600,
        'max_sessions': 100000,
        'new_sessions_per_sec': 15000,
        'max_ipsec_tunnels': 500,
        'max_security_rules': 10000,
        'recommended_role': 'branch',
        'form_factor': 'Virtual (2 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'sdwan_rules': 64,
        'sdwan_virtual_interfaces': 32,
        'max_zones': 32,
        'max_virtual_routers': 2,
        'use_case': 'Cloud branch, SD-WAN edge in cloud',
        'description': 'Mid-range VM for branch or SD-WAN edge',
    }),
    ('VM-300', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 4000,
        'threat_throughput': 2000,
        'ipsec_vpn_throughput': 3000,
        'ssl_decrypt_throughput': 1200,
        'max_sessions': 250000,
        'new_sessions_per_sec': 30000,
        'max_ipsec_tunnels': 2000,
        'max_security_rules': 10000,
        'recommended_role': 'both',
        'form_factor': 'Virtual (4 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'sdwan_rules': 128,
        'sdwan_virtual_interfaces': 64,
        'max_zones': 64,
        'max_virtual_routers': 5,
        'use_case': 'Cloud hub, enterprise cloud gateway',
        'description': 'Enterprise VM for branch or small hub',
    }),
    ('VM-500', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 8000,
        'threat_throughput': 4000,
        'ipsec_vpn_throughput': 5000,
        'ssl_decrypt_throughput': 2400,
        'max_sessions': 800000,
        'new_sessions_per_sec': 120000,
        'max_ipsec_tunnels': 4000,
        'max_security_rules': 20000,
        'recommended_role': 'both',
        'form_factor': 'Virtual (8 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'sdwan_rules': 256,
        'sdwan_virtual_interfaces': 128,
        'max_zones': 128,
        'max_virtual_routers': 10,
        'use_case': 'Cloud hub, datacenter edge, multi-cloud gateway',
        'description': 'High-performance VM for hub or datacenter edge',
    }),
    ('VM-700', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 16000,
        'threat_throughput': 8000,
        'ipsec_vpn_throughput': 10000,
        'ssl_decrypt_throughput': 4800,
        'max_sessions': 1800000,
        'new_sessions_per_sec': 200000,
        'max_ipsec_tunnels': 8000,
        'max_security_rules': 40000,
        'recommended_role': 'hub',
        'form_factor': 'Virtual (16 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'sdwan_rules': 512,
        'sdwan_virtual_interfaces': 256,
        'max_zones': 256,
        'max_virtual_routers': 20,
        'use_case': 'Large cloud hub, datacenter aggregation',
        'description': 'Large VM for datacenter hub deployments',
    }),
    ('VM-1000-HV', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 20000,
        'threat_throughput': 10000,
        'ipsec_vpn_throughput': 12000,
        'ssl_decrypt_throughput': 6000,
        'max_sessions': 2500000,
        'new_sessions_per_sec': 250000,
        'max_ipsec_tunnels': 12000,
        'max_security_rules': 60000,
        'recommended_role': 'hub',
        'form_factor': 'Virtual (16+ vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'sdwan_rules': 512,
        'sdwan_virtual_interfaces': 256,
        'max_zones': 256,
        'max_virtual_routers': 20,
        'use_case': 'Largest cloud hub, high-capacity aggregation',
        'description': 'Largest VM for high-capacity SD-WAN hubs',
    }),
])


LICENSE_RECOMMENDATIONS = {
    'sdwan': {
        'name': 'SD-WAN License',
        'description': 'Required subscription for SD-WAN functionality on PAN-OS firewalls',
        'required': True,
    },
    'threat_prevention': {
        'name': 'Threat Prevention',
        'description': 'IPS, anti-malware, command-and-control protection',
        'required': False,
    },
    'dns_security': {
        'name': 'DNS Security',
        'description': 'DNS-layer threat protection and analytics',
        'required': False,
    },
    'wildfire': {
        'name': 'WildFire',
        'description': 'Cloud-based malware analysis and zero-day prevention',
        'required': False,
    },
    'url_filtering': {
        'name': 'Advanced URL Filtering',
        'description': 'Web content filtering and phishing prevention',
        'required': False,
    },
    'ssl_decryption': {
        'name': 'SSL Decryption',
        'description': 'SSL Forward Proxy and Inbound Inspection for encrypted traffic visibility',
        'required': False,
    },
    'bpla': {
        'name': 'BPLA (Bundle)',
        'description': 'Best Practice License Agreement — includes Threat Prevention, WildFire, URL Filtering, DNS Security, and SD-WAN',
        'required': False,
    },
    'adem': {
        'name': 'ADEM (Autonomous DEM)',
        'description': 'Autonomous Digital Experience Management for SD-WAN monitoring',
        'required': False,
    },
}

# Security features that affect sizing throughput
SECURITY_FEATURES = OrderedDict([
    ('threat_prevention', {
        'label': 'Threat Prevention',
        'description': 'IPS, Anti-Virus, Anti-Spyware, C2 Protection',
        'throughput_key': 'threat_throughput',
        'impact': 'high',
    }),
    ('ssl_decryption', {
        'label': 'SSL Decryption',
        'description': 'SSL Forward Proxy / Inbound Inspection',
        'throughput_key': 'ssl_decrypt_throughput',
        'impact': 'high',
    }),
    ('url_filtering', {
        'label': 'URL Filtering',
        'description': 'Web Content Filtering, Anti-Phishing',
        'throughput_key': None,
        'impact': 'medium',
    }),
    ('wildfire', {
        'label': 'WildFire',
        'description': 'Cloud Malware Analysis, Zero-Day Prevention',
        'throughput_key': None,
        'impact': 'medium',
    }),
    ('dns_security', {
        'label': 'DNS Security',
        'description': 'DNS-Layer Threat Protection',
        'throughput_key': None,
        'impact': 'low',
    }),
])


# Spec display names and units for dashboard/report
SPEC_DISPLAY = OrderedDict([
    ('firewall_throughput', {'label': 'Firewall Throughput', 'unit': 'Mbps'}),
    ('threat_throughput', {'label': 'Threat Prevention Throughput', 'unit': 'Mbps'}),
    ('ssl_decrypt_throughput', {'label': 'SSL Decryption Throughput', 'unit': 'Mbps'}),
    ('ipsec_vpn_throughput', {'label': 'IPSec VPN Throughput', 'unit': 'Mbps'}),
    ('max_sessions', {'label': 'Max Concurrent Sessions', 'unit': ''}),
    ('new_sessions_per_sec', {'label': 'New Sessions/Second', 'unit': '/sec'}),
    ('max_ipsec_tunnels', {'label': 'Max IPSec Tunnels', 'unit': ''}),
    ('max_security_rules', {'label': 'Max Security Rules', 'unit': ''}),
    ('sdwan_rules', {'label': 'SD-WAN Policy Rules', 'unit': ''}),
    ('sdwan_virtual_interfaces', {'label': 'SD-WAN Virtual Interfaces', 'unit': ''}),
    ('max_zones', {'label': 'Max Security Zones', 'unit': ''}),
    ('max_virtual_routers', {'label': 'Max Virtual Routers', 'unit': ''}),
    ('ports', {'label': 'Network Ports', 'unit': ''}),
    ('form_factor', {'label': 'Form Factor', 'unit': ''}),
    ('power_supply', {'label': 'Power Supply', 'unit': ''}),
])
