"""PA Firewall model specifications for sizing calculations.

Specs sourced from Palo Alto Networks product datasheets.
All throughput values in Mbps. Session counts are maximums.
"""

from collections import OrderedDict

# TAC recommended PAN-OS versions per series
TAC_RECOMMENDED_PANOS = OrderedDict([
    ('PA-400', '11.1.6 or 11.2.4'),
    ('PA-800', '11.1.6 or 11.2.4'),
    ('PA-1400', '11.2.4 or 12.0.1'),
    ('PA-3400', '11.1.6 or 11.2.4'),
    ('PA-5400', '11.1.6 or 11.2.4'),
    ('PA-7000', '11.1.6 or 11.2.4'),
    ('VM-Series', '11.1.6 or 11.2.4'),
])

# Hardware models — ordered smallest to largest
PA_MODELS = OrderedDict([
    ('PA-440', {
        'series': 'PA-400',
        'platform': 'hardware',
        'firewall_throughput': 3700,
        'threat_throughput': 920,
        'ipsec_vpn_throughput': 1800,
        'ssl_decrypt_throughput': 550,
        'max_sessions': 200000,
        'new_sessions_per_sec': 39000,
        'max_ipsec_tunnels': 250,
        'max_security_rules': 3000,
        'recommended_role': 'branch',
        'form_factor': 'Desktop',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G',
        'power_supply': 'Single',
        'description': 'Entry-level branch firewall for small offices',
    }),
    ('PA-450', {
        'series': 'PA-400',
        'platform': 'hardware',
        'firewall_throughput': 5200,
        'threat_throughput': 1600,
        'ipsec_vpn_throughput': 3100,
        'ssl_decrypt_throughput': 960,
        'max_sessions': 300000,
        'new_sessions_per_sec': 52000,
        'max_ipsec_tunnels': 500,
        'max_security_rules': 5000,
        'recommended_role': 'branch',
        'form_factor': 'Desktop',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 1G',
        'power_supply': 'Single',
        'description': 'Mid-range branch firewall for medium offices',
    }),
    ('PA-460', {
        'series': 'PA-400',
        'platform': 'hardware',
        'firewall_throughput': 7400,
        'threat_throughput': 2400,
        'ipsec_vpn_throughput': 4700,
        'ssl_decrypt_throughput': 1440,
        'max_sessions': 400000,
        'new_sessions_per_sec': 74000,
        'max_ipsec_tunnels': 1000,
        'max_security_rules': 7500,
        'recommended_role': 'branch',
        'form_factor': 'Desktop',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '12x 1G, 4x PoE',
        'power_supply': 'Single',
        'description': 'High-performance branch firewall',
    }),
    ('PA-820', {
        'series': 'PA-800',
        'platform': 'hardware',
        'firewall_throughput': 2100,
        'threat_throughput': 960,
        'ipsec_vpn_throughput': 1100,
        'ssl_decrypt_throughput': 580,
        'max_sessions': 192000,
        'new_sessions_per_sec': 26000,
        'max_ipsec_tunnels': 500,
        'max_security_rules': 5000,
        'recommended_role': 'branch',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '4x 1G, 4x SFP',
        'power_supply': 'Redundant',
        'description': 'Rack-mount branch firewall with redundant power',
    }),
    ('PA-850', {
        'series': 'PA-800',
        'platform': 'hardware',
        'firewall_throughput': 3200,
        'threat_throughput': 1500,
        'ipsec_vpn_throughput': 1900,
        'ssl_decrypt_throughput': 900,
        'max_sessions': 384000,
        'new_sessions_per_sec': 38000,
        'max_ipsec_tunnels': 1000,
        'max_security_rules': 10000,
        'recommended_role': 'branch',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '4x 1G, 4x SFP, 2x 10G SFP+',
        'power_supply': 'Redundant',
        'description': 'High-end branch firewall with 10G uplinks',
    }),
    ('PA-1410', {
        'series': 'PA-1400',
        'platform': 'hardware',
        'firewall_throughput': 5400,
        'threat_throughput': 2300,
        'ipsec_vpn_throughput': 3000,
        'ssl_decrypt_throughput': 1200,
        'max_sessions': 400000,
        'new_sessions_per_sec': 68000,
        'max_ipsec_tunnels': 1000,
        'max_security_rules': 10000,
        'recommended_role': 'both',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '4x 1G, 4x 2.5G, 4x SFP+',
        'power_supply': 'Single',
        'description': 'Entry-level enterprise branch or small hub firewall',
    }),
    ('PA-1420', {
        'series': 'PA-1400',
        'platform': 'hardware',
        'firewall_throughput': 11000,
        'threat_throughput': 3900,
        'ipsec_vpn_throughput': 5600,
        'ssl_decrypt_throughput': 2500,
        'max_sessions': 800000,
        'new_sessions_per_sec': 100000,
        'max_ipsec_tunnels': 2000,
        'max_security_rules': 12500,
        'recommended_role': 'both',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '4x 1G, 4x 2.5G/5G, 4x SFP+',
        'power_supply': 'Redundant',
        'description': 'Enterprise branch or small hub firewall',
    }),
    ('PA-3410', {
        'series': 'PA-3400',
        'platform': 'hardware',
        'firewall_throughput': 18500,
        'threat_throughput': 5200,
        'ipsec_vpn_throughput': 9300,
        'ssl_decrypt_throughput': 3400,
        'max_sessions': 1500000,
        'new_sessions_per_sec': 175000,
        'max_ipsec_tunnels': 4000,
        'max_security_rules': 20000,
        'recommended_role': 'both',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '12x 1G, 4x SFP+, 2x QSFP28',
        'power_supply': 'Redundant',
        'description': 'Mid-enterprise firewall for hub or large branch',
    }),
    ('PA-3420', {
        'series': 'PA-3400',
        'platform': 'hardware',
        'firewall_throughput': 24500,
        'threat_throughput': 6800,
        'ipsec_vpn_throughput': 12600,
        'ssl_decrypt_throughput': 4500,
        'max_sessions': 2000000,
        'new_sessions_per_sec': 235000,
        'max_ipsec_tunnels': 6000,
        'max_security_rules': 25000,
        'recommended_role': 'hub',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '12x 1G, 8x SFP+, 4x QSFP28',
        'power_supply': 'Redundant',
        'description': 'Enterprise hub firewall',
    }),
    ('PA-3430', {
        'series': 'PA-3400',
        'platform': 'hardware',
        'firewall_throughput': 31000,
        'threat_throughput': 10000,
        'ipsec_vpn_throughput': 16100,
        'ssl_decrypt_throughput': 6500,
        'max_sessions': 2500000,
        'new_sessions_per_sec': 295000,
        'max_ipsec_tunnels': 8000,
        'max_security_rules': 30000,
        'recommended_role': 'hub',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '12x 1G, 8x SFP+, 4x QSFP28',
        'power_supply': 'Redundant',
        'description': 'Large enterprise hub firewall',
    }),
    ('PA-3440', {
        'series': 'PA-3400',
        'platform': 'hardware',
        'firewall_throughput': 38000,
        'threat_throughput': 12500,
        'ipsec_vpn_throughput': 20200,
        'ssl_decrypt_throughput': 8200,
        'max_sessions': 3000000,
        'new_sessions_per_sec': 358000,
        'max_ipsec_tunnels': 10000,
        'max_security_rules': 40000,
        'recommended_role': 'hub',
        'form_factor': '1U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '12x 1G, 12x SFP+, 4x QSFP28',
        'power_supply': 'Redundant',
        'description': 'Top-of-line PA-3400 series for large hubs',
    }),
    ('PA-5410', {
        'series': 'PA-5400',
        'platform': 'hardware',
        'firewall_throughput': 55000,
        'threat_throughput': 22500,
        'ipsec_vpn_throughput': 29000,
        'ssl_decrypt_throughput': 15000,
        'max_sessions': 6000000,
        'new_sessions_per_sec': 550000,
        'max_ipsec_tunnels': 16000,
        'max_security_rules': 60000,
        'recommended_role': 'hub',
        'form_factor': '2U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '2x 100G QSFP28, 8x 10G/25G SFP28, 12x 1G/10G',
        'power_supply': 'Redundant',
        'description': 'High-performance datacenter/hub firewall',
    }),
    ('PA-5420', {
        'series': 'PA-5400',
        'platform': 'hardware',
        'firewall_throughput': 72000,
        'threat_throughput': 33000,
        'ipsec_vpn_throughput': 38000,
        'ssl_decrypt_throughput': 22000,
        'max_sessions': 9000000,
        'new_sessions_per_sec': 700000,
        'max_ipsec_tunnels': 24000,
        'max_security_rules': 80000,
        'recommended_role': 'hub',
        'form_factor': '2U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '4x 100G QSFP28, 16x 10G/25G SFP28, 12x 1G/10G',
        'power_supply': 'Redundant',
        'description': 'Large datacenter/regional hub firewall',
    }),
    ('PA-5430', {
        'series': 'PA-5400',
        'platform': 'hardware',
        'firewall_throughput': 97000,
        'threat_throughput': 43000,
        'ipsec_vpn_throughput': 52000,
        'ssl_decrypt_throughput': 29000,
        'max_sessions': 13000000,
        'new_sessions_per_sec': 900000,
        'max_ipsec_tunnels': 32000,
        'max_security_rules': 100000,
        'recommended_role': 'hub',
        'form_factor': '2U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 100G QSFP28, 16x 10G/25G SFP28, 12x 1G/10G',
        'power_supply': 'Redundant',
        'description': 'High-end datacenter/SD-WAN hub firewall',
    }),
    ('PA-5440', {
        'series': 'PA-5400',
        'platform': 'hardware',
        'firewall_throughput': 120000,
        'threat_throughput': 56000,
        'ipsec_vpn_throughput': 68000,
        'ssl_decrypt_throughput': 37000,
        'max_sessions': 18000000,
        'new_sessions_per_sec': 1100000,
        'max_ipsec_tunnels': 40000,
        'max_security_rules': 120000,
        'recommended_role': 'hub',
        'form_factor': '2U Rack',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': '8x 100G QSFP28, 16x 10G/25G SFP28, 12x 1G/10G',
        'power_supply': 'Redundant',
        'description': 'Top PA-5400 series datacenter firewall',
    }),
    ('PA-7050', {
        'series': 'PA-7000',
        'platform': 'hardware',
        'firewall_throughput': 300000,
        'threat_throughput': 135000,
        'ipsec_vpn_throughput': 150000,
        'ssl_decrypt_throughput': 90000,
        'max_sessions': 50000000,
        'new_sessions_per_sec': 2500000,
        'max_ipsec_tunnels': 60000,
        'max_security_rules': 200000,
        'recommended_role': 'hub',
        'form_factor': '12U Chassis',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Modular (NPCs)',
        'power_supply': 'Redundant',
        'description': 'Chassis-based firewall for largest SD-WAN hubs',
    }),
    ('PA-7080', {
        'series': 'PA-7000',
        'platform': 'hardware',
        'firewall_throughput': 700000,
        'threat_throughput': 310000,
        'ipsec_vpn_throughput': 350000,
        'ssl_decrypt_throughput': 207000,
        'max_sessions': 100000000,
        'new_sessions_per_sec': 5000000,
        'max_ipsec_tunnels': 120000,
        'max_security_rules': 400000,
        'recommended_role': 'hub',
        'form_factor': '19U Chassis',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Modular (NPCs)',
        'power_supply': 'Redundant',
        'description': 'Largest chassis-based firewall for massive deployments',
    }),
])

# VM-Series models — ordered smallest to largest
VM_MODELS = OrderedDict([
    ('VM-50', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 200,
        'threat_throughput': 100,
        'ipsec_vpn_throughput': 100,
        'ssl_decrypt_throughput': 60,
        'max_sessions': 50000,
        'new_sessions_per_sec': 3000,
        'max_ipsec_tunnels': 250,
        'max_security_rules': 2500,
        'recommended_role': 'branch',
        'form_factor': 'Virtual (2 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'description': 'Smallest VM for lab, dev, or micro-branch',
    }),
    ('VM-100', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 2000,
        'threat_throughput': 1000,
        'ipsec_vpn_throughput': 1000,
        'ssl_decrypt_throughput': 600,
        'max_sessions': 50000,
        'new_sessions_per_sec': 3000,
        'max_ipsec_tunnels': 500,
        'max_security_rules': 5000,
        'recommended_role': 'branch',
        'form_factor': 'Virtual (2 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'description': 'Small VM for branch or remote sites',
    }),
    ('VM-200', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 2000,
        'threat_throughput': 1000,
        'ipsec_vpn_throughput': 1000,
        'ssl_decrypt_throughput': 600,
        'max_sessions': 100000,
        'new_sessions_per_sec': 15000,
        'max_ipsec_tunnels': 500,
        'max_security_rules': 10000,
        'recommended_role': 'branch',
        'form_factor': 'Virtual (2 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'description': 'Mid-range VM for branch or SD-WAN edge',
    }),
    ('VM-300', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 4000,
        'threat_throughput': 2000,
        'ipsec_vpn_throughput': 3000,
        'ssl_decrypt_throughput': 1200,
        'max_sessions': 250000,
        'new_sessions_per_sec': 30000,
        'max_ipsec_tunnels': 2000,
        'max_security_rules': 10000,
        'recommended_role': 'both',
        'form_factor': 'Virtual (4 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'description': 'Enterprise VM for branch or small hub',
    }),
    ('VM-500', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 8000,
        'threat_throughput': 4000,
        'ipsec_vpn_throughput': 5000,
        'ssl_decrypt_throughput': 2400,
        'max_sessions': 800000,
        'new_sessions_per_sec': 120000,
        'max_ipsec_tunnels': 4000,
        'max_security_rules': 20000,
        'recommended_role': 'both',
        'form_factor': 'Virtual (8 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'description': 'High-performance VM for hub or datacenter edge',
    }),
    ('VM-700', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 16000,
        'threat_throughput': 8000,
        'ipsec_vpn_throughput': 10000,
        'ssl_decrypt_throughput': 4800,
        'max_sessions': 1800000,
        'new_sessions_per_sec': 200000,
        'max_ipsec_tunnels': 8000,
        'max_security_rules': 40000,
        'recommended_role': 'hub',
        'form_factor': 'Virtual (16 vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'description': 'Large VM for datacenter hub deployments',
    }),
    ('VM-1000-HV', {
        'series': 'VM-Series',
        'platform': 'virtual',
        'firewall_throughput': 20000,
        'threat_throughput': 10000,
        'ipsec_vpn_throughput': 12000,
        'ssl_decrypt_throughput': 6000,
        'max_sessions': 2500000,
        'new_sessions_per_sec': 250000,
        'max_ipsec_tunnels': 12000,
        'max_security_rules': 60000,
        'recommended_role': 'hub',
        'form_factor': 'Virtual (16+ vCPU)',
        'ha_supported': True,
        'sdwan_supported': True,
        'ports': 'Virtual NICs',
        'power_supply': 'N/A',
        'description': 'Largest VM for high-capacity SD-WAN hubs',
    }),
])


LICENSE_RECOMMENDATIONS = {
    'sdwan': {
        'name': 'SD-WAN License',
        'description': 'Required subscription for SD-WAN functionality on PAN-OS firewalls',
        'required': True,
    },
    'threat_prevention': {
        'name': 'Threat Prevention',
        'description': 'IPS, anti-malware, command-and-control protection',
        'required': False,
    },
    'dns_security': {
        'name': 'DNS Security',
        'description': 'DNS-layer threat protection and analytics',
        'required': False,
    },
    'wildfire': {
        'name': 'WildFire',
        'description': 'Cloud-based malware analysis and zero-day prevention',
        'required': False,
    },
    'url_filtering': {
        'name': 'Advanced URL Filtering',
        'description': 'Web content filtering and phishing prevention',
        'required': False,
    },
    'ssl_decryption': {
        'name': 'SSL Decryption',
        'description': 'SSL Forward Proxy and Inbound Inspection for encrypted traffic visibility',
        'required': False,
    },
    'bpla': {
        'name': 'BPLA (Bundle)',
        'description': 'Best Practice License Agreement — includes Threat Prevention, WildFire, URL Filtering, DNS Security, and SD-WAN',
        'required': False,
    },
    'adem': {
        'name': 'ADEM (Autonomous DEM)',
        'description': 'Autonomous Digital Experience Management for SD-WAN monitoring',
        'required': False,
    },
}

# Security features that affect sizing throughput
SECURITY_FEATURES = OrderedDict([
    ('threat_prevention', {
        'label': 'Threat Prevention',
        'description': 'IPS, Anti-Virus, Anti-Spyware, C2 Protection',
        'throughput_key': 'threat_throughput',
        'impact': 'high',
    }),
    ('ssl_decryption', {
        'label': 'SSL Decryption',
        'description': 'SSL Forward Proxy / Inbound Inspection',
        'throughput_key': 'ssl_decrypt_throughput',
        'impact': 'high',
    }),
    ('url_filtering', {
        'label': 'URL Filtering',
        'description': 'Web Content Filtering, Anti-Phishing',
        'throughput_key': None,
        'impact': 'medium',
    }),
    ('wildfire', {
        'label': 'WildFire',
        'description': 'Cloud Malware Analysis, Zero-Day Prevention',
        'throughput_key': None,
        'impact': 'medium',
    }),
    ('dns_security', {
        'label': 'DNS Security',
        'description': 'DNS-Layer Threat Protection',
        'throughput_key': None,
        'impact': 'low',
    }),
])


# Spec display names and units for dashboard/report
SPEC_DISPLAY = OrderedDict([
    ('firewall_throughput', {'label': 'Firewall Throughput', 'unit': 'Mbps'}),
    ('threat_throughput', {'label': 'Threat Prevention Throughput', 'unit': 'Mbps'}),
    ('ssl_decrypt_throughput', {'label': 'SSL Decryption Throughput', 'unit': 'Mbps'}),
    ('ipsec_vpn_throughput', {'label': 'IPSec VPN Throughput', 'unit': 'Mbps'}),
    ('max_sessions', {'label': 'Max Concurrent Sessions', 'unit': ''}),
    ('new_sessions_per_sec', {'label': 'New Sessions/Second', 'unit': '/sec'}),
    ('max_ipsec_tunnels', {'label': 'Max IPSec Tunnels', 'unit': ''}),
    ('max_security_rules', {'label': 'Max Security Rules', 'unit': ''}),
    ('ports', {'label': 'Network Ports', 'unit': ''}),
    ('form_factor', {'label': 'Form Factor', 'unit': ''}),
    ('power_supply', {'label': 'Power Supply', 'unit': ''}),
])
